// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $CFGNavWrapper from "./islands/CFGNavWrapper.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $DisassemblyEffect from "./islands/DisassemblyEffect.tsx";
import * as $HexDecoder from "./islands/HexDecoder.tsx";
import * as $JointJSComponent from "./islands/JointJSComponent.tsx";
import * as $NameCycle from "./islands/NameCycle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CFGNavWrapper.tsx": $CFGNavWrapper,
    "./islands/Counter.tsx": $Counter,
    "./islands/DisassemblyEffect.tsx": $DisassemblyEffect,
    "./islands/HexDecoder.tsx": $HexDecoder,
    "./islands/JointJSComponent.tsx": $JointJSComponent,
    "./islands/NameCycle.tsx": $NameCycle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
