// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $Home from "./routes/Home.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $projects from "./routes/projects.tsx";
import * as $writeups_ctf_slug_ from "./routes/writeups/[ctf]/[slug].tsx";
import * as $writeups_index from "./routes/writeups/index.tsx";
import * as $HomeInteractive from "./islands/HomeInteractive.tsx";
import * as $JointJSComponent from "./islands/JointJSComponent.tsx";
import * as $NameCycle from "./islands/NameCycle.tsx";
import * as $WriteupPage from "./islands/WriteupPage.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/Home.tsx": $Home,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/projects.tsx": $projects,
    "./routes/writeups/[ctf]/[slug].tsx": $writeups_ctf_slug_,
    "./routes/writeups/index.tsx": $writeups_index,
  },
  islands: {
    "./islands/HomeInteractive.tsx": $HomeInteractive,
    "./islands/JointJSComponent.tsx": $JointJSComponent,
    "./islands/NameCycle.tsx": $NameCycle,
    "./islands/WriteupPage.tsx": $WriteupPage,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
